# Generated by Django 5.1.1 on 2024-10-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfcmtoken',
            name='token',
            field=models.CharField(max_length=1024, unique=True, verbose_name='Token'),
        ),
    ]
